{% set name = "pythermo" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythermo-{{ version }}.tar.gz
  sha256: 3cf9b0fd51d8e949ad44ca0ce0c09892bdcc3dbeea37a6a9ce476318e472a9c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - pythermo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pythermo/
  summary: Tools for performing computational tasks in the field of low-temperature thermochronology.
  dev_url: https://github.com/OpenThermochronology/PyThermo
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrguenthner
