{% set name = "pythermo" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythermo-{{ version }}.tar.gz
  sha256: dc5ebd2b0be85f8bf2def61044973bebf07a9366a2151020ad4539dcfdd443ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - pythermo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pythermo/
  summary: Tools for performing computational tasks in the field of low-temperature thermochronology.
  dev_url: https://github.com/OpenThermochronology/PyThermo
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrguenthner
